libs-$(CONFIG_LIB_SEL4_ARM_VMM) += libsel4arm-vmm

libsel4arm-vmm: common $(libc) libutils libsel4utils libsel4vka libsel4vspace libsel4dma libsel4vmmcore
libsel4arm-vmm: libsel4simple libplatsupport

ifeq ($(CONFIG_LIB_USB),y)
libsel4arm-vmm: libusbdrivers
endif

ifeq ($(CONFIG_LIB_SEL4_ARM_VMM_VCHAN_SUPPORT),y)
libsel4arm-vmm: libsel4vchan
endif
