#!/usr/bin/sh

qemu-system-aarch64 \
    --kernel images/sel4arm-vmm-image-arm-zynqmp \
    --cpu cortex-a53 \
    --machine xlnx-zcu102,virtualization=on \
    -m 4096 \
    -nographic \
    # -s -S
